version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - chatbook

# ######################################################################
# Job Definitions
# Each job is keyed with a unique name, and sequenced in the workflows
# section. Should any run step fail within a job, then that step will be
# marked as a failure
# ######################################################################
jobs:
  chatbook:
    docker:
      - image: node:10.13.0
    working_directory: ~/chatbook
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn install
      - run: yarn ci
